language: node_js
node_js:
  - 18.15.0
cache: npm

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: dist
  keep-history: true
  on:
    branch: main

branches:
  except:
    - /^pull\//
