language: node_js
node_js:
  - 20
cache: yarn

install:
  - yarn install

script:
  - yarn build

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: dist
  keep-history: true
  on:
    branch: main
