name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run prod

    - name: Trigger "pages-build-deployment" workflow
      uses: actions/workflow-dispatch@v2
      with:
        workflow: pages-build-deployment
        token: ${{ secrets.GITHUB_TOKEN }}

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
